// Exercise library — ported verbatim from the original Ascend app.js
// (categories, muscle groups, and ~150 exercises preserved exactly).

export const EX: Record<string,{e:string;m:string;x:string[]}> ={
  "Chest":{e:"💪",m:"Pecs · Triceps · Shoulders",x:["Bench Press","Incline Bench Press","Decline Bench Press","Dumbbell Bench Press","Incline Dumbbell Press","Dumbbell Flyes","Cable Crossover","Chest Dips","Push-Ups","Incline Push-Ups","Wide Push-Ups","Diamond Push-Ups","Machine Chest Press","Pec Deck"]},
  "Back":{e:"🏋️",m:"Lats · Traps · Rhomboids",x:["Barbell Row","Dumbbell Row","Seated Cable Row","T-Bar Row","Lat Pulldown","Wide-Grip Pulldown","Close-Grip Pulldown","Pull-Ups","Chin-Ups","Assisted Pull-Ups","Face Pulls","Straight-Arm Pulldown","Deadlift","Romanian Deadlift","Rack Pulls","Good Mornings","Hyperextensions","Machine Row"]},
  "Shoulders":{e:"🔝",m:"Delts · Traps",x:["Barbell Overhead Press","Dumbbell Shoulder Press","Arnold Press","Seated Dumbbell Press","Push Press","Lateral Raises","Cable Lateral Raise","Front Raises","Rear Delt Flyes","Reverse Pec Deck","Upright Rows","Machine Shoulder Press","Shrugs"]},
  "Legs":{e:"🦵",m:"Quads · Hamstrings · Glutes · Calves",x:["Barbell Squat","Goblet Squat","Hack Squat","Front Squat","Bulgarian Split Squat","Walking Lunges","Reverse Lunges","Side Lunges","Leg Press","Leg Extension","Leg Curl","Romanian Deadlift","Stiff-Leg Deadlift","Hip Thrust","Glute Bridge","Step-Ups","Calf Raises","Seated Calf Raises","Box Jumps","Wall Sit","Nordic Curl"]},
  "Biceps":{e:"💪",m:"Biceps · Forearms",x:["Barbell Curl","EZ-Bar Curl","Dumbbell Curl","Hammer Curl","Incline Dumbbell Curl","Preacher Curl","Concentration Curl","Cable Curl","Zottman Curl","Spider Curl"]},
  "Triceps":{e:"💪",m:"Triceps",x:["Tricep Pushdown","Rope Pushdown","Overhead Tricep Extension","Skull Crushers","Close-Grip Bench Press","Dips","Tricep Kickbacks","Diamond Push-Ups","Cable Overhead Extension","Machine Dip"]},
  "Core":{e:"🔥",m:"Abs · Obliques",x:["Plank","Side Plank","Farmer's Carry","Suitcase Carry","Hollow Hold","Dead Bug","Crunches","Bicycle Crunches","Reverse Crunches","Leg Raises","Hanging Leg Raises","Russian Twists","Ab Wheel Rollout","Cable Crunch","V-Ups","Mountain Climbers","Flutter Kicks","Dragon Flag","Pallof Press"]},
  "Cardio":{e:"🏃",m:"Cardiovascular",x:["Treadmill Walk","Treadmill Run","Incline Walk","Stairmaster","Stationary Bike","Rowing Machine","Elliptical","Jump Rope","Box Jumps","Burpees","Battle Ropes","Sled Push","Sprint Intervals","Swimming","Cycling","Ski Erg"]},
  "Outdoor & Activities":{e:"🌿",m:"Full Body · Cardio · Fun",x:["Walking","Jogging","Running","Hiking","Cycling (Outdoor)","Swimming (Outdoor)","Basketball","Soccer","Tennis","Pickleball","Volleyball","Dancing","Yoga","Pilates","Rock Climbing","Kayaking","Paddleboarding","Jump Rope (Outdoor)","Martial Arts","Boxing","CrossFit","Circuit Training","HIIT Class","Spin Class","Zumba","Stretching / Mobility","Foam Rolling","Skateboarding","Surfing","Skiing / Snowboarding"]},
  "Olympic / Power":{e:"⚡",m:"Full Body",x:["Power Clean","Hang Clean","Clean & Jerk","Snatch","Push Press","Push Jerk","Kettlebell Swing","Kettlebell Clean","Turkish Get-Up","Sandbag Carry","Landmine Press","Landmine Row","Landmine Single Arm Row","Landmine Squat","Landmine Rotation","Landmine Deadlift","Landmine Thruster"]}
};

// Category display order per workout type
export const TO: Record<string,string[]> ={"Full Body":["Legs","Chest","Back","Shoulders","Biceps","Triceps","Core","Cardio","Outdoor & Activities","Olympic / Power"],"Lower Body + Core":["Legs","Core","Cardio","Outdoor & Activities","Back","Shoulders","Chest","Biceps","Triceps","Olympic / Power"],"Upper Body + Conditioning":["Chest","Back","Shoulders","Biceps","Triceps","Core","Cardio","Outdoor & Activities","Legs","Olympic / Power"],"Cardio Only":["Outdoor & Activities","Cardio","Core","Legs","Chest","Back","Shoulders","Biceps","Triceps","Olympic / Power"],"Rest / Active Recovery":["Outdoor & Activities","Core","Cardio","Legs","Chest","Back","Shoulders","Biceps","Triceps","Olympic / Power"],"Other":["Outdoor & Activities","Chest","Back","Legs","Shoulders","Biceps","Triceps","Core","Cardio","Olympic / Power"]};

export const WORKOUT_TYPES = Object.keys(TO)
export const MEAL_TYPES = ["Breakfast","Morning Snack","Lunch","Afternoon Snack","Dinner","Evening Snack","Pre-Workout","Post-Workout"]
